### ISSUE TITLE
Empty dependencies break type inference

### ISSUE THREAD

**Issue by ecamellini** [buildo/avenger#161]
## description

Passing empty `dependencies` objects results in a `QueryReturn<any, ...>` type:

![](https://i.gyazo.com/df49195ff787a7de33a5329d85914e38.gif)

## how to reproduce
- {optional: describe steps to reproduce defect}

## specs
{optional: describe a possible fix for this defect, if not obvious}

## misc
{optional: other useful info}

**Comment by giogonzo** [comment]
closing because it doesn't affect version 5
