### ISSUE TITLE
QueryReturn and CommandReturn types are assignable one to the other

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/avenger#166]
## description
It means that TS does not complain if I try to pass a command to `react-avenger/declareQueries` or a query to `declareCommands` resulting in a weird runtime error

## how to reproduce
```ts
const queries = declareCommands({ myQuery }); // NO errror
const commands = declareQueries({ myCommand }); // NO errror
```

## specs
It could be sufficient to add a tag to the `QueryReturn` and `CommandReturn` types
```tsx
export interface QueryReturn<A, P> {
  _tag: 'QueryReturn', // similarly for `CommandReturn`
  _A: A,
  _P: P
}
```

## misc
{optional: other useful info}

**Comment by giogonzo** [comment]
moving to the appropriate repo: https://github.com/buildo/react-avenger/issues/63
