### ISSUE TITLE
WithQueries: honor the last "render" prop received

### ISSUE THREAD

**Issue by giogonzo** [buildo/avenger#214]
Currently, `WithQuery` caches via `useMemo` the `declareQueries` invocation, and thus also the actual `render()` as specified by the user.
This is not desired and might result in inadvertently closing over values defined outside of the `WithQuery` scope.

Tagging as "bug" because, even if this was really just unspecified before, this is probably not the expected behavior

Solution: use an additional `useRef`/`useEffect` couple in order to keep track of the latest `render` prop, without dropping the `declareQueries` memoization

**Comment by veej** [comment]
Still not working. The `useEffect` will change the ref after the render function is called.
We should completely remove the `useEffect`, or try to replace it with a `useLayoutEffect` (that should run synchronously before the render function is called)
