### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by utaal** [buildo/avenger#24]
- [ ] add caching config to `Query`
- [ ] set up caching data structures
- [ ] update serialized recipe
- [ ] change `avenger.schedule` to be aware of the cache

**Comment by giogonzo** [comment]
- [x] add caching config to `Query`
- [ ] set up caching data structures
- [ ] update serialized recipe
- [x] change `avenger.schedule` to be aware of the cache
- [ ] write an *actualizeCache* function

**Comment by giogonzo** [comment]
So I realized that caching done this way it's useless - doesn't solve our problems
What we need to serialize is just the `fetchParams` result when we have the cached result for the dependency, not the whole actualized cache..

Was thinking of rewriting everything (now that we have a better understanding of the toy) to be split in more fine grained processing steps; the serialization/recipe part should be handled as optional step(s).

Something like:
```
[ input: AvengerInput(queries+params, implicitState), cache: ActualizableCache ]
build upset
[ input: AvengerInput(more queries+params, implicitState), cache: ActualizableCache ]
actualize cache
[ input: AvengerInput(queries+params, implicitState), cache: ActualizedCache ]
actualize fetchParams of cached dependents
[ input: AvengerActualizedInput(queries+params, implicitState, actualized fetchParams) ]

(de)serializable: recipe is AvengerActualizedInput

[ input: AvengerActualizedInput(queries+params, implicitState, actualized fetchParams) ]
build upset (not sure if recipe contains upset queries or only declared ones - should anyway be idempotent)
[ input: AvengerActualizedInput(queries+params, implicitState, actualized fetchParams) ]
actualize parameters
[ input: AvengerFetcherInput(fetcher queries, implicitState, actualized fetchParams) ]
schedule
```

**Comment by utaal** [comment]
We went for a different approach, where outputs of each steps are represented separately, and later steps accept everything they need as inputs.
