### ISSUE TITLE
Rename Query 'cache' parameter into 'cacheStrategy' or 'cacheMode'

### ISSUE THREAD

**Issue by gabro** [buildo/avenger#93]
IMHO `cache` is unclear.

The tcomb type is `CacheMode`, so `cacheMode` is probably a better name for the parameter.

`cacheStrategy` is another good alternative (longer to type, though).

Thoughts? @giogonzo

**Comment by giogonzo** [comment]
done in future versions, it is called `cacheStrategy` now
