### ISSUE TITLE
Provide precise type for Query `fetch`

### ISSUE THREAD

**Issue by gabro** [buildo/avenger#94]
`fetch` currently has type `t.Function`.

The actual type is:

```
t.Object -> t.Object -> Promise
```

Can we express this with tcomb?

**Comment by giogonzo** [comment]
and same goes for `Command.run`

**Comment by giogonzo** [comment]
the actual type now is something like `{ [T in keyof Params&Dependencies] } -> Promise<ReturnType>`

This is something that will definitely be taken care of when rewriting in TS or adding typings in general
